language: c
env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.12
    - RACKET_VERSION=7.0
    - RACKET_VERSION=7.1
    - RACKET_VERSION=7.2
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
#   - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash 
- export PATH="${RACKET_DIR}/bin:${PATH}" 

install:
 - raco pkg install --auto --name racket-predicates

before_script:

script:
 - raco test -x -p racket-predicates

after_success:
 - raco setup --check-pkg-deps --pkgs racket-predicates
 - raco pkg install --auto cover cover-coveralls
 - raco cover -b -f coveralls -d $TRAVIS_BUILD_DIR/coverage .
